Update Gmic-Qt to last 4.0.3

diff --git a/gmicqt/gmic/resources/gmic_buildpackage b/gmicqt/gmic/resources/gmic_buildpackage
--- a/gmicqt/gmic/resources/gmic_buildpackage
+++ b/gmicqt/gmic/resources/gmic_buildpackage
@@ -41,6 +41,10 @@
 #  knowledge of the CeCILL license and that you accept its terms.
 #
 
+set -euo pipefail
+trap 'echo "Error line $LINENO : command \"$BASH_COMMAND\" failed"' ERR
+MODE=${1:-}
+
 # Handle package building on Windows.
 #------------------------------------
 if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
@@ -75,10 +79,10 @@ if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
     VERSION=${RELEASE1}${RELEASE2}${RELEASE3}
     SVERSION=${RELEASE1}.${RELEASE2}.${RELEASE3}
 
-    GIMPTOOL=$(command -v gimptool-3.0 >/dev/null && echo gimptool-3.0 || echo gimptool-2.0)
+    GIMPTOOL=$(command -v gimptool-3.2 >/dev/null && echo gimptool-3.2 || echo gimptool-2.0)
     GIMPVER=$(echo `$GIMPTOOL --version` | cut -d. -f1-2)
 
-    if [ "$1" == "final" ]; then
+    if [ "$MODE" == "final" ]; then
         SUFFIX="";
         sed "s/PRERELEASE_CFLAGS = /NO_PRERELEASE_CFLAGS = /" Makefile > /tmp/Makefile
         mv /tmp/Makefile Makefile
@@ -99,7 +103,7 @@ if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
     cp -rf /e/work/src/gmic/resources/gmic_scale2x_cnn.gmz $HOME/build${BITS}-gimp
     cp -rf /e/work/src/gmic/resources/gmic_fonts.gmz $HOME/build${BITS}-gimp
     cp -rf /e/work/src/gmic/resources/gmic_lightleaks.gmz $HOME/build${BITS}-gimp
-    rm -rf $HOME/build${BITS}-gimp/update*.gmic gmic_*${SVERSION}${SUFFIX}*_win${BITS}* gmic-*${SVERSION}${SUFFIX}*-win${BITS}*
+    rm -rf $HOME/build${BITS}-gimp/update*.gmic gmic_*${SVERSION}${SUFFIX}*_win${BITS}* gmic-*${SVERSION}${SUFFIX}*-win${BITS}* *.iss
     sed s\/XXX\/${SVERSION}${SUFFIX}\/g /e/work/src/gmic/resources/gmic_gimp${GIMPVER}_win${BITS}.iss > tmp.iss &&
         sed s\/xxx\/${VERSION}\/g tmp.iss > installer.iss
 
@@ -119,11 +123,11 @@ if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
 
     # Generate binaries.
     cd $HOME/gmic/src && make CXX="clang++" clean && rm -f gmic *.o && cp -f /e/work/src/CImg/CImg.h .
-    if [[ "$GIMPVER" != "3.0" ]]; then
+    if [[ "$GIMPVER" != "2.10" ]]; then
         make CXX="clang++" EXTRA_CFLAGS="-m${BITS}" cli lib libc # libc_static
     fi
     cd $HOME/gmic-qt && rm -rf .obj
-    if [ "$1" == "final" ]; then
+    if [ "$MODE" == "final" ]; then
         qmake COMPILER=clang PRERELEASE= HOST=none gmic_qt.pro && make clean
         sed "s/-fno-keep-inline-dllexport //" Makefile.Release > /tmp/Makefile
         mv /tmp/Makefile Makefile.Release
@@ -145,7 +149,7 @@ if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
 
     # Copy binaries into their respective folders.
     cd $HOME
-    if [[ "$GIMPVER" != "3.0" ]]; then
+    if [[ "$GIMPVER" != "2.10" ]]; then
         cp -f gmic/src/gmic.exe build${BITS}-cli/
         cp -f gmic/src/gmic.h gmic/src/gmic_libc.h gmic/src/use_lib* gmic/src/lib*.d* gmic/src/lib*.a build${BITS}-lib/
         cp -f gmic-qt/release/gmic_qt.exe build${BITS}-qt/
@@ -153,7 +157,7 @@ if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
     cp -f gmic-qt/release/gmic_gimp_qt.exe build${BITS}-gimp/
 
     # Construct G'MIC (CLI) archive.
-    if [[ "$GIMPVER" != "3.0" ]]; then
+    if [[ "$GIMPVER" != "2.10" ]]; then
         cp -rf build${BITS}-cli ${OUTDIR_CLI} &&
             cp -f /e/work/src/gmic/COPYING ${OUTDIR_CLI} &&
             sed s\/_gmic_version\/${SVERSION}${SUFFIX}\/ /e/work/src/gmic/README > ${OUTDIR_CLI}/README &&
@@ -162,7 +166,7 @@ if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
     fi
 
     # Construct G'MIC (LIB) archive.
-    if [[ "$GIMPVER" != "3.0" ]]; then
+    if [[ "$GIMPVER" != "2.10" ]]; then
         cp -rf build${BITS}-lib ${OUTDIR_LIB} &&
             cp -f /e/work/src/gmic/COPYING ${OUTDIR_LIB} &&
             sed s\/_gmic_version\/${SVERSION}${SUFFIX}\/ /e/work/src/gmic/README > ${OUTDIR_LIB}/README &&
@@ -171,7 +175,7 @@ if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
     fi
 
     # Construct G'MIC (Qt standalone) archive.
-    if [[ "$GIMPVER" != "3.0" ]]; then
+    if [[ "$GIMPVER" != "2.10" ]]; then
         cp -rf build${BITS}-qt ${OUTDIR_QT} &&
             cp -f /e/work/src/gmic/COPYING ${OUTDIR_QT} &&
             sed s\/_gmic_version\/${SVERSION}${SUFFIX}\/ /e/work/src/gmic/README > ${OUTDIR_QT}/README &&
@@ -201,16 +205,20 @@ fi
 #-----------------------------------------------------
 DIST=`lsb_release -d | tail -c+13 | xargs`
 BITS=`uname -m`
+IS_320=$(grep '(3)' /usr/include/gimp-3.2/libgimpbase/gimpversion.h 2>/dev/null | wc -l || true)
+IS_300=$(grep '(3)' /usr/include/gimp-3.0/libgimpbase/gimpversion.h 2>/dev/null | wc -l || true)
+IS_210=$(grep '(10)' /usr/include/gimp-2.0/libgimpbase/gimpversion.h 2>/dev/null | wc -l || true)
 
-IS_300=`grep \(3\) /usr/include/gimp-3.0/libgimpbase/gimpversion.h | wc -l`
-IS_210=`grep \(10\) /usr/include/gimp-2.0/libgimpbase/gimpversion.h | wc -l`
-
-if [ "$IS_300" == "1" ]; then GIMPVER=3.0
+if [ "$IS_320" == "1" ]; then GIMPVER=3.2
+elif [ "$IS_300" == "1" ]; then GIMPVER=3.0
 elif [ "$IS_210" == "1" ]; then GIMPVER=2.10
 else GIMPVER=2.8
 fi
 
-if [ "$HOSTNAME" != "C302L-G17P17.png.unicaen.fr" ] && [ "$HOSTNAME" != "C302L-G14F15.png.unicaen.fr" ] && [ "$HOSTNAME" != "C302L-G23P04.png.unicaen.fr" ]; then
+if [ "$HOSTNAME" != "C302L-G26P03.png.unicaen.fr" ] &&
+   [ "$HOSTNAME" != "C302L-G17P17.png.unicaen.fr" ] &&
+   [ "$HOSTNAME" != "C302L-G14F15.png.unicaen.fr" ] &&
+   [ "$HOSTNAME" != "C302L-G23P04.png.unicaen.fr" ]; then
     SF_HOME=/media/sf_tschumperle
     cd ${SF_HOME}/work/src
     RELEASE0=`grep "#define gmic_version" gmic/src/gmic.h | tail -c5`
@@ -223,7 +231,7 @@ if [ "$HOSTNAME" != "C302L-G17P17.png.unicaen.fr" ] && [ "$HOSTNAME" != "C302L-G
     CODENAME="${CODENAME//./-}"
     BITS=`uname -m`
     if [ "$BITS" == "x86_64" ]; then BITS=64; ARCH=amd64; PARCH=x86_64; else BITS=32; ARCH=i386; PARCH=i386; fi
-    if [ "$1" == "final" ]; then SUFFIX=""; else SUFFIX=_pre; fi
+    if [ "$MODE" == "final" ]; then SUFFIX=""; else SUFFIX=_pre; fi
 
     TARFILE=gmic_${SVERSION}${SUFFIX}.tar
     OUTDIR=gmic-${SVERSION}${SUFFIX}
@@ -235,26 +243,28 @@ if [ "$HOSTNAME" != "C302L-G17P17.png.unicaen.fr" ] && [ "$HOSTNAME" != "C302L-G
     echo "> Bits = $BITS"
     echo "> GIMP version = $GIMPVER"
     echo "> Output .tar file = '$TARFILE'"
-    echo "> Output directory = '$OUTDIR/'"
+    echo "> Output directory = '/tmp/$OUTDIR/'"
     echo "> Output package = '$OUTPAK'"
     echo "> Output GIMP plugin = '$OUTZIP_GIMP'"
 
     while [ ! -f deb_${TARFILE}.gz ]; do sleep 10; done
     sleep 10
-    cp deb_${TARFILE}.gz /tmp/ &&
-        cd /tmp/ &&
-        rm -rf gmic_gimp_qt $OUTDIR $OUTPAK $OUTZIP_GIMP $GENERIC_OUTZIP_GIMP &&
-        touch deb_${TARFILE}.gz &&
-        tar zxvf deb_${TARFILE}.gz &&
-        find gmic-${SVERSION}${SUFFIX} -exec touch {} ;
+    cp deb_${TARFILE}.gz /tmp/
+    cd /tmp/
+    rm -rf gmic_gimp_qt $OUTDIR $OUTPAK $OUTZIP_GIMP $GENERIC_OUTZIP_GIMP *.deb
+    touch deb_${TARFILE}.gz
+    tar zxvf deb_${TARFILE}.gz
+    find gmic-${SVERSION}${SUFFIX} -exec touch {} || true
 
     cd $OUTDIR/src
-    sed "s/\$(MAKE) lib cli gimp gmic_qt libc/\$(MAKE) lib cli_shared gimp_shared gmic_qt_shared libc/g" Makefile > /tmp/Makefile && mv /tmp/Makefile Makefile;
-    sed "s/\&\& \$(MAKE) clean//g" Makefile > /tmp/Makefile && mv /tmp/Makefile Makefile;  # Prevent 'qmake not found' bug when using dpkg-buildpackage, still don't know why.
+    sed "s/\$(MAKE) lib cli gimp gmic_qt libc/\$(MAKE) lib cli_shared gimp_shared gmic_qt_shared libc/g" Makefile > /tmp/Makefile
+    mv /tmp/Makefile Makefile;
+    sed "s/\&\& \$(MAKE) clean//g" Makefile > /tmp/Makefile
+    mv /tmp/Makefile Makefile;  # Prevent 'qmake not found' bug when using dpkg-buildpackage, still don't know why.
 
-    cd /tmp/$OUTDIR &&
-        dpkg-buildpackage -d -j4 -rfakeroot;
-    mv ../gmic_${SVERSION}_${ARCH}.deb ../$OUTPAK
+    cd /tmp/$OUTDIR
+    dpkg-buildpackage -d -j4 -rfakeroot
+    mv ../gmic_*.deb ../$OUTPAK
     cp -f ../$OUTPAK $SF_HOME/work/src/
 
     mkdir -p gmic_gimp_qt
@@ -283,7 +293,7 @@ CODENAME=`. /etc/os-release && echo "${ID}${VERSION_ID}_${VERSION_CODENAME}"`
 CODENAME="${CODENAME//./-}"
 BITS=`uname -m`
 if [ "$BITS" == "x86_64" ]; then BITS=64; ARCH=amd64; PARCH=x86_64; else BITS=32; ARCH=i386; PARCH=i386; fi
-if [ "$1" == "final" ]; then SUFFIX=""; LSUFFIX=""; else SUFFIX=_pre; LSUFFIX=_pre`date +%y%m%d%H`; fi
+if [ "$MODE" == "final" ]; then SUFFIX=""; LSUFFIX=""; else SUFFIX=_pre; LSUFFIX=_pre`date +%y%m%d%H`; fi
 DIR=/tmp/gmic-${SVERSION}${SUFFIX}
 rm -f gmic_*${SVERSION}${SUFFIX}* deb_gmic_*
 
@@ -294,17 +304,17 @@ echo " - Release number : $SVERSION$SUFFIX"
 #----------------------------------------
 echo " - Merge 'develop' and 'master' branches."
 cd CImg
-git checkout master
-git merge develop -m "."
-git push
-git checkout develop
+git checkout master || true
+git merge develop -m "." || true
+git push || true
+git checkout develop || true
 cd ..
 
 cd gmic
-git checkout master
-git merge develop -m "."
-git push
-git checkout develop
+git checkout master || true
+git merge develop -m "." || true
+git push || true
+git checkout develop || true
 rm -rf gmic-qt
 ln -fs ../gmic-qt .
 
@@ -334,20 +344,18 @@ ln -fs ../../gmic-community/libcgmic/gmic_libc.h .
 ln -fs ../../gmic-community/libcgmic/use_libcgmic.c .
 gmic _version=$VERSION update_instimg
 
-if [ "$1" == "final" ]; then
+if [ "$MODE" == "final" ]; then
     gmic _update_header_html ../html/header.html,${VERSION},0
     gmic _update_header_html ../html/header1.html,${VERSION},0
-    git push --delete origin v.$VERSION
-    git pull
-    git tag -d v.$SVERSION
-    git tag v.$SVERSION
+    git push --delete origin v.$VERSION || true
+    git pull || true
+    git tag -d v.$SVERSION || true
+    git tag v.$SVERSION || true
     gmic_commit "Final release "${SVERSION}
-    git push --tags
-#    COMMIT=$(git -C $HOME/work/src/gmic-qt log -1 | head -1 | cut -d' ' -f 2)  # Get the SHA1 of the latest commit
-#    wget -O /dev/null --timeout=10 "${GMIC_FOUREY_URL}?version=v.${SVERSION}&commit=${COMMIT}"
-else
-    gmic _update_header_html ../html/header.html,${VERSION},1
-    gmic _update_header_html ../html/header1.html,${VERSION},1
+    git push --tags || true
+#else
+#    gmic _update_header_html ../html/header.html,${VERSION},1
+#    gmic _update_header_html ../html/header1.html,${VERSION},1
 fi
 gmic_commit "Auto-commit for release "${SVERSION}${SUFFIX}
 
@@ -364,10 +372,10 @@ echo " - Upload G'MIC web page."
 cd html
 rm -rf gallery color_presets reference tutorial
 lftp sftp://$GMIC_LOGIN:@ovh -e "mirror -RL . /home/"$GMIC_LOGIN"/www/gmic/ ; quit"
-lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/gallery/ header1.html; quit";
-lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/color_presets/ header1.html; quit";
-lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/reference/ header1.html; quit";
-lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/tutorial/ header1.html; quit";
+lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/gallery/ header1.html footer.html; quit";
+lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/color_presets/ header1.html footer.html; quit";
+lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/reference/ header1.html footer.html; quit";
+lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/tutorial/ header1.html footer.html; quit";
 rm -f gmic_stdlib.gmic gmic_stdlib.$VERSION
 cd ..
 cd resources/samples
@@ -383,6 +391,7 @@ cp -Lrf COPYING README CONTRIBUTING.md Makefile cmake CMakeLists.txt $DIR
 
 cd src
 mkdir -p $DIR/src
+make CImg.h gmic_stdlib_community.h
 cp -Lrf Makefile CImg.h gmic.cpp gmic.h gmic_stdlib_community.h gmic_stdlib.gmic gmic_cli.cpp gmic_in_script.scm use_libgmic.cpp gmic_libc.cpp gmic_libc.h use_libcgmic.c $DIR/src
 touch $DIR/src/gmic_stdlib_community.h
 cd ..
@@ -394,7 +403,7 @@ cd ..
 
 cd resources
 mkdir -p $DIR/resources
-cp -Lrf gmic_bashcompletion.sh gmic_cluts.gmz gmic_demos.cimgz gmic_denoise_cnn.gmz gmic_scale2x_cnn.gmz gmic_fonts.gmz gmic_lightleaks.gmz $DIR/resources
+cp -Lrf gmic_bashcompletion.sh gmic_cluts.gmz gmic_demos.cimgz gmic_denoise_cnn.gmz gmic_scale2x_cnn.gmz gmic_fonts.gmz gmic_lightleaks.gmz gmic-mode.el $DIR/resources
 mkdir -p $DIR/resources/samples
 cp -Lrf samples/*.gmic $DIR/resources/samples
 cp -Lrf debian $DIR
@@ -421,7 +430,7 @@ sed s\/_gmic_version\/$SVERSION\/ changelog > /tmp/changelog
 mv /tmp/changelog changelog
 
 cd $DIR/src
-if [ "$1" == "final" ]; then
+if [ "$MODE" == "final" ]; then
     sed "s/PRERELEASE_CFLAGS = /NO_PRERELEASE_CFLAGS = /" Makefile > /tmp/Makefile
     mv /tmp/Makefile Makefile
     sed "s/PRERELEASE = /NO_PRERELEASE = /" Makefile > /tmp/Makefile
@@ -429,19 +438,18 @@ if [ "$1" == "final" ]; then
 fi
 sed "s/rm -rf CImg.h gmic_stdlib_community.h /rm -rf /" Makefile > /tmp/Makefile
 mv /tmp/Makefile Makefile
-make clean
-rm -f gmic_buildpackage
 for i in *.h *.cpp *.c *.gmic *.scm; do
-    sed -e 's/ *$//' $i >/tmp/gmic_buildpackage$$ && mv /tmp/gmic_buildpackage$$ $i
+    sed -e 's/ *$//' $i >/tmp/gmic_buildpackage$$
+    mv /tmp/gmic_buildpackage$$ $i
 done
 
 cd $DIR
 rm -rf debian/gmic
-rm -f `find . -name ".?*"`
-rm -f `find . -name "*~"`
-rm -r `find . -name "\#*"`
-rm -r `find . -name "CVS"`
-rm -r `find . -name ".git"`
+rm -f `find . -name ".?*"` || true
+rm -f `find . -name "*~"` || true
+rm -r `find . -name "\#*"` || true
+rm -r `find . -name "CVS"` || true
+rm -r `find . -name ".git"` || true
 
 # Create .tar.gz source archives.
 #--------------------------------
@@ -462,7 +470,7 @@ tar chvf ${TARFILE} `basename $DIR`
 gzip ${TARFILE}
 cp -f ${TARFILE}.gz ${HOME}/work/src/
 
-if [ "$1" == "final" ]; then
+if [ "$MODE" == "final" ]; then
     lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/files/source/ ${HOME}/work/src/${TARFILE}.gz; quit";
 fi
 
@@ -470,33 +478,7 @@ lftp sftp://$GMIC_LOGIN:@ovh -e "mrm /home/"$GMIC_LOGIN"/www/gmic/files/prerelea
 lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/files/prerelease ${HOME}/work/src/${TARFILE}.gz -o gmic_prerelease.tar.gz; quit"
 lftp sftp://$GMIC_LOGIN:@ovh -e "put -O /home/"$GMIC_LOGIN"/www/gmic/files/prerelease ${HOME}/work/src/${TARFILE}.gz -o gmic_${SVERSION}${LSUFFIX}.tar.gz; quit"
 
-# Create debian packages for debian/ubuntu 64 bits.
-#--------------------------------------------------
-echo " - Create debian packages."
-
-cp ${HOME}/work/src/deb_${TARFILE}.gz /tmp/ &&
-    cd /tmp/ &&
-    OUTPAK=gmic_${SVERSION}${SUFFIX}_${CODENAME}_${ARCH}.deb &&
-    OUTZIP_GIMP=gmic_${SVERSION}${SUFFIX}_gimp${GIMPVER}_${CODENAME}_${ARCH}.zip &&
-    OUTDIR=gmic-${SVERSION}${SUFFIX} &&
-    rm -rf gmic_gimp_qt $OUTPAK $OUTZIP_GIMP &&
-    touch deb_${TARFILE}.gz &&
-    tar zxvf deb_${TARFILE}.gz &&
-    find gmic-${SVERSION}${SUFFIX} -exec touch {} \; &&
-    cd $OUTDIR/src &&
-    sed "s/\$(MAKE) lib cli gimp gmic_qt libc/\$(MAKE) lib cli_shared gimp_shared gmic_qt_shared libc/g" Makefile > /tmp/Makefile &&
-    mv /tmp/Makefile Makefile && cd ../..
-cd $OUTDIR &&
-    dpkg-buildpackage -d -j4 -rfakeroot;
-    mv ../gmic_${SVERSION}_amd64.deb ../$OUTPAK &&
-    mkdir -p gmic_gimp_qt &&
-    rm -f gmic-qt/gmic_gimp_qt &&
-    make gimp &&
-    cp -f gmic-qt/gmic_gimp_qt README gmic_gimp_qt/ &&
-    zip -r -9 ../$OUTZIP_GIMP gmic_gimp_qt &&
-    cp -f ../$OUTPAK ../$OUTZIP_GIMP $HOME/work/src/
-
-echo ELARA_DONE
+echo MAIN_DONE
 
 # Wait for packages to be generated from Virtual machines, and copy them to G'MIC server.
 #----------------------------------------------------------------------------------------
